version: "3.9"

services:
  db:
    image: postgres:16
    container_name: wallet-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: wallet-app
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/wallet
      SECRET: supersecret
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
